-- SQLite to MySQL data export
-- Generated: 2026-04-09 12:17:15
-- Import: mysql -u root iriseuroperevival < database/mysql_import.sql

SET FOREIGN_KEY_CHECKS = 0;

-- faqs (9 rows)
TRUNCATE TABLE `faqs`;
INSERT INTO `faqs` (`id`, `question`, `answer`, `category`, `sort_order`, `is_published`, `translations`, `created_at`, `updated_at`) VALUES ('1', 'Who can attend Europe Revival 2026?', 'Europe Revival is open to everyone—believers, seekers, church leaders, and anyone hungry for an encounter with God. Whether you''re a seasoned minister or new to faith, you''re welcome to join us in Budapest.', 'general', '1', '1', NULL, '2026-01-27 13:55:25', '2026-01-27 13:55:25');
INSERT INTO `faqs` (`id`, `question`, `answer`, `category`, `sort_order`, `is_published`, `translations`, `created_at`, `updated_at`) VALUES ('2', 'Will there be a livestream available?', 'Yes! Main sessions will be livestreamed for those who cannot attend in person. However, we highly encourage in-person attendance to fully experience the atmosphere of revival and receive personal ministry.', 'general', '3', '1', NULL, '2026-01-27 13:55:25', '2026-02-20 15:24:46');
INSERT INTO `faqs` (`id`, `question`, `answer`, `category`, `sort_order`, `is_published`, `translations`, `created_at`, `updated_at`) VALUES ('3', 'What languages will be available?', 'The conference will be held in English with simultaneous translation available in Hungarian, German, Romanian, and Russian. Translation devices will be provided at the venue.', 'general', '4', '1', NULL, '2026-01-27 13:55:25', '2026-02-20 15:24:46');
INSERT INTO `faqs` (`id`, `question`, `answer`, `category`, `sort_order`, `is_published`, `translations`, `created_at`, `updated_at`) VALUES ('4', 'Is childcare available?', 'Yes, we will have a supervised children''s program for ages 4-12 during main sessions. Registration for childcare is required in advance. Children under 4 must be accompanied by a parent or guardian.', 'general', '5', '1', NULL, '2026-01-27 13:55:25', '2026-02-20 15:24:46');
INSERT INTO `faqs` (`id`, `question`, `answer`, `category`, `sort_order`, `is_published`, `translations`, `created_at`, `updated_at`) VALUES ('5', 'Are meals included?', 'Meals are not included in the registration fee. However, there will be food vendors on-site, and the venue is surrounded by restaurants and cafes. We''ll also have a coffee shop area for fellowship during breaks.', 'general', '6', '1', NULL, '2026-01-27 13:55:25', '2026-02-20 15:24:46');
INSERT INTO `faqs` (`id`, `question`, `answer`, `category`, `sort_order`, `is_published`, `translations`, `created_at`, `updated_at`) VALUES ('6', 'How do I apply to Volunteer?', 'Volunteer applications are open! Complete our application form and tell us how you would like to serve. Approved volunteers receive a 20% discount on the ticket and a free event t-shirt. Applications close September 1, 2026.', 'volunteer', '7', '1', NULL, '2026-01-27 13:55:25', '2026-02-20 15:24:46');
INSERT INTO `faqs` (`id`, `question`, `answer`, `category`, `sort_order`, `is_published`, `translations`, `created_at`, `updated_at`) VALUES ('7', 'Where can I stay if I''m coming for multiple days?', 'Budapest offers a wide range of accommodation options to suit every budget. From affordable hostels and Airbnb apartments to hotels near the venue, you''ll find plenty of choices. We''ll share a list of recommended accommodations closer to the event.', 'general', '8', '1', NULL, '2026-02-06 17:39:08', '2026-02-20 15:24:46');
INSERT INTO `faqs` (`id`, `question`, `answer`, `category`, `sort_order`, `is_published`, `translations`, `created_at`, `updated_at`) VALUES ('8', 'Where is the conference held?', 'Europe Revival 2026 will be held at BOK Csarnok in Budapest, Hungary.

Address: Budapest, Dózsa György út 1, 1146', 'general', '2', '1', NULL, '2026-02-06 17:39:08', '2026-02-20 15:24:46');
INSERT INTO `faqs` (`id`, `question`, `answer`, `category`, `sort_order`, `is_published`, `translations`, `created_at`, `updated_at`) VALUES ('10', 'How can I support the work of Iris?', 'If you would like to support the mission of Iris, you can find more information at iriskrakow.org. Your generosity helps bring light to the darkness, healing to the broken, and love to the unloved across Europe.', 'general', '10', '1', NULL, '2026-02-20 15:24:46', '2026-02-20 15:24:46');

-- registrations (5 rows)
TRUNCATE TABLE `registrations`;
INSERT INTO `registrations` (`id`, `uuid`, `type`, `status`, `first_name`, `last_name`, `email`, `phone`, `country`, `city`, `ticket_type`, `ticket_quantity`, `amount`, `citizenship`, `languages`, `occupation`, `church_name`, `church_city`, `pastor_name`, `pastor_email`, `is_born_again`, `is_spirit_filled`, `testimony`, `attended_ministry_school`, `ministry_school_name`, `reference_1_name`, `reference_1_email`, `reference_2_name`, `reference_2_email`, `stripe_session_id`, `stripe_payment_intent`, `paid_at`, `approved_at`, `approved_by`, `rejected_at`, `rejected_by`, `rejection_reason`, `admin_notes`, `created_at`, `updated_at`, `user_id`, `stripe_customer_id`, `invited_by`, `reference_1_contacted_at`, `reference_1_status`, `reference_1_response`, `reference_2_contacted_at`, `reference_2_status`, `reference_2_response`, `confirmation_email_sent_at`, `service_areas`, `has_served_before`, `previous_service_description`, `wants_to_evangelize`, `want_to_healing_room`, `want_to_prophet_room`) VALUES ('1', 'e8ab1d30-f447-44d2-bfb1-122786432088', 'attendee', 'pending_payment', 'sdfsf', 'sdfsf', 'a@a.prb', '234245653', 'Hungary', 'dfgdfgdf', 'individual', '1', '4900', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '0', NULL, NULL, NULL, NULL, NULL, 'cs_test_b12qgffsBtf1kUk2NJr3h2ID7aXwJY4DUPs1kVVx5H6oONHxSTBKQYIFwi', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-02-12 13:54:02', '2026-02-12 13:54:04', NULL, 'cus_TxwDw2SkvDY50x', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-02-12 13:54:02', NULL, '0', NULL, '0', '0', '0');
INSERT INTO `registrations` (`id`, `uuid`, `type`, `status`, `first_name`, `last_name`, `email`, `phone`, `country`, `city`, `ticket_type`, `ticket_quantity`, `amount`, `citizenship`, `languages`, `occupation`, `church_name`, `church_city`, `pastor_name`, `pastor_email`, `is_born_again`, `is_spirit_filled`, `testimony`, `attended_ministry_school`, `ministry_school_name`, `reference_1_name`, `reference_1_email`, `reference_2_name`, `reference_2_email`, `stripe_session_id`, `stripe_payment_intent`, `paid_at`, `approved_at`, `approved_by`, `rejected_at`, `rejected_by`, `rejection_reason`, `admin_notes`, `created_at`, `updated_at`, `user_id`, `stripe_customer_id`, `invited_by`, `reference_1_contacted_at`, `reference_1_status`, `reference_1_response`, `reference_2_contacted_at`, `reference_2_status`, `reference_2_response`, `confirmation_email_sent_at`, `service_areas`, `has_served_before`, `previous_service_description`, `wants_to_evangelize`, `want_to_healing_room`, `want_to_prophet_room`) VALUES ('2', 'd4971d86-bfdd-46f5-884a-4289633709fe', 'ministry', 'pending_approval', 'gfhgf', 'sdfsf', 'a@a.prb', '3435656', 'Hungary', 'ssfdgh', NULL, '1', NULL, 'hu', '["English"]', 'hvjh', 'jhgjhg', 'jkjhljb', 'kjhkjhk', 'a@a.prb', '1', '1', 'jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl jhgjgjgjljl ', '1', 'jkgjg', 'jhgjhg', 'a@a.prb', 'khkjhkjh', 'a@a.prb', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-02-12 14:10:51', '2026-02-12 14:10:51', NULL, NULL, 'ngjkgk', NULL, 'pending', NULL, NULL, 'pending', NULL, '2026-02-12 14:10:51', NULL, '0', NULL, '0', '0', '0');
INSERT INTO `registrations` (`id`, `uuid`, `type`, `status`, `first_name`, `last_name`, `email`, `phone`, `country`, `city`, `ticket_type`, `ticket_quantity`, `amount`, `citizenship`, `languages`, `occupation`, `church_name`, `church_city`, `pastor_name`, `pastor_email`, `is_born_again`, `is_spirit_filled`, `testimony`, `attended_ministry_school`, `ministry_school_name`, `reference_1_name`, `reference_1_email`, `reference_2_name`, `reference_2_email`, `stripe_session_id`, `stripe_payment_intent`, `paid_at`, `approved_at`, `approved_by`, `rejected_at`, `rejected_by`, `rejection_reason`, `admin_notes`, `created_at`, `updated_at`, `user_id`, `stripe_customer_id`, `invited_by`, `reference_1_contacted_at`, `reference_1_status`, `reference_1_response`, `reference_2_contacted_at`, `reference_2_status`, `reference_2_response`, `confirmation_email_sent_at`, `service_areas`, `has_served_before`, `previous_service_description`, `wants_to_evangelize`, `want_to_healing_room`, `want_to_prophet_room`) VALUES ('3', '07b3240e-0b49-49b9-8df7-69a66734881a', 'volunteer', 'pending_approval', 'fdgsfdgs', 'sdfgsfdgsd', 'a@a.prb', '3452453', 'Hungary', 'dsfsfd', NULL, '1', NULL, NULL, '["English"]', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-02-23 15:40:11', '2026-02-23 15:40:11', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-02-23 15:40:11', '["Registration"]', '1', 'sfdgdhg', '0', '0', '0');
INSERT INTO `registrations` (`id`, `uuid`, `type`, `status`, `first_name`, `last_name`, `email`, `phone`, `country`, `city`, `ticket_type`, `ticket_quantity`, `amount`, `citizenship`, `languages`, `occupation`, `church_name`, `church_city`, `pastor_name`, `pastor_email`, `is_born_again`, `is_spirit_filled`, `testimony`, `attended_ministry_school`, `ministry_school_name`, `reference_1_name`, `reference_1_email`, `reference_2_name`, `reference_2_email`, `stripe_session_id`, `stripe_payment_intent`, `paid_at`, `approved_at`, `approved_by`, `rejected_at`, `rejected_by`, `rejection_reason`, `admin_notes`, `created_at`, `updated_at`, `user_id`, `stripe_customer_id`, `invited_by`, `reference_1_contacted_at`, `reference_1_status`, `reference_1_response`, `reference_2_contacted_at`, `reference_2_status`, `reference_2_response`, `confirmation_email_sent_at`, `service_areas`, `has_served_before`, `previous_service_description`, `wants_to_evangelize`, `want_to_healing_room`, `want_to_prophet_room`) VALUES ('4', '1880dfbe-1e79-4408-87f3-08c71f2030f3', 'attendee', 'pending_payment', 'fdhggdfh', 'fgdhdfgh', 'a@a.prb', '452352', 'Hungary', 'dfsgd', 'individual', '1', '4900', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '0', NULL, NULL, NULL, NULL, NULL, 'cs_test_b1xH9xFcbvc5g63JvPfJvBF2c0EcIatSRgQokd01iUKZAHv9Quhbvf760z', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-02-23 16:39:36', '2026-02-23 16:39:38', NULL, 'cus_TxwDw2SkvDY50x', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-02-23 16:39:36', NULL, '0', NULL, '0', '0', '0');
INSERT INTO `registrations` (`id`, `uuid`, `type`, `status`, `first_name`, `last_name`, `email`, `phone`, `country`, `city`, `ticket_type`, `ticket_quantity`, `amount`, `citizenship`, `languages`, `occupation`, `church_name`, `church_city`, `pastor_name`, `pastor_email`, `is_born_again`, `is_spirit_filled`, `testimony`, `attended_ministry_school`, `ministry_school_name`, `reference_1_name`, `reference_1_email`, `reference_2_name`, `reference_2_email`, `stripe_session_id`, `stripe_payment_intent`, `paid_at`, `approved_at`, `approved_by`, `rejected_at`, `rejected_by`, `rejection_reason`, `admin_notes`, `created_at`, `updated_at`, `user_id`, `stripe_customer_id`, `invited_by`, `reference_1_contacted_at`, `reference_1_status`, `reference_1_response`, `reference_2_contacted_at`, `reference_2_status`, `reference_2_response`, `confirmation_email_sent_at`, `service_areas`, `has_served_before`, `previous_service_description`, `wants_to_evangelize`, `want_to_healing_room`, `want_to_prophet_room`) VALUES ('5', '310ee04c-4d08-4dbd-be4a-af5dfd740de9', 'volunteer', 'pending_approval', 'Tóth', 'Tamás', 'tamas@cegem360.hu', '+36203319550', 'Hungary', 'Budapest', NULL, '1', NULL, NULL, '["Romanian"]', NULL, NULL, NULL, NULL, NULL, '0', '0', NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-03-11 14:44:53', '2026-03-11 14:44:53', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-03-11 14:44:53', '["Childcare"]', '1', 'no', '0', '0', '0');

-- schedule_items (21 rows)
TRUNCATE TABLE `schedule_items`;
INSERT INTO `schedule_items` (`id`, `title`, `description`, `day`, `start_time`, `end_time`, `type`, `speaker_id`, `location`, `translations`, `created_at`, `updated_at`, `is_published`, `sort_order`) VALUES ('29', 'Registration & Check-in', NULL, '2026-10-22 00:00:00', '09:00', '10:00', 'special', NULL, NULL, NULL, '2026-02-04 20:00:11', '2026-03-03 12:27:52', '1', '0');
INSERT INTO `schedule_items` (`id`, `title`, `description`, `day`, `start_time`, `end_time`, `type`, `speaker_id`, `location`, `translations`, `created_at`, `updated_at`, `is_published`, `sort_order`) VALUES ('30', 'Ministry Team Training Day', 'Training for ministry team members and volunteers with David Gava and Iris ministry team leaders. (Lunch break included.)', '2026-10-22 00:00:00', '10:00', '17:00', 'session', NULL, NULL, NULL, '2026-02-04 20:00:11', '2026-03-03 12:27:52', '1', '1');
INSERT INTO `schedule_items` (`id`, `title`, `description`, `day`, `start_time`, `end_time`, `type`, `speaker_id`, `location`, `translations`, `created_at`, `updated_at`, `is_published`, `sort_order`) VALUES ('31', 'Lunch Break', NULL, '2026-10-22 00:00:00', '12:30', '13:30', 'meal', NULL, NULL, NULL, '2026-02-04 20:00:11', '2026-03-03 12:27:52', '0', '2');
INSERT INTO `schedule_items` (`id`, `title`, `description`, `day`, `start_time`, `end_time`, `type`, `speaker_id`, `location`, `translations`, `created_at`, `updated_at`, `is_published`, `sort_order`) VALUES ('32', 'Pastors & Leaders Session', 'Special session for pastors, ministry leaders and business leaders with coffee, tea, and refreshments.

Participation in this presentation is possible only with an invitation.', '2026-10-23 00:00:00', '11:00', '14:00', 'session', '2', 'Main Hall', NULL, '2026-02-04 20:00:11', '2026-03-03 12:53:11', '1', '0');
INSERT INTO `schedule_items` (`id`, `title`, `description`, `day`, `start_time`, `end_time`, `type`, `speaker_id`, `location`, `translations`, `created_at`, `updated_at`, `is_published`, `sort_order`) VALUES ('33', 'Opening Session', 'Worship, Guest Speaker and Ministry Time', '2026-10-23 00:00:00', '18:30', '22:00', 'session', NULL, 'Main Hall', NULL, '2026-02-04 20:00:11', '2026-02-20 15:03:12', '1', '1');
INSERT INTO `schedule_items` (`id`, `title`, `description`, `day`, `start_time`, `end_time`, `type`, `speaker_id`, `location`, `translations`, `created_at`, `updated_at`, `is_published`, `sort_order`) VALUES ('34', 'Saturday Morning Main Session', 'Worship, Guest Speaker and Ministry Time', '2026-10-24 00:00:00', '09:00', '12:00', 'session', NULL, 'Main Hall', NULL, '2026-02-04 20:00:11', '2026-02-20 15:03:12', '1', '0');
INSERT INTO `schedule_items` (`id`, `title`, `description`, `day`, `start_time`, `end_time`, `type`, `speaker_id`, `location`, `translations`, `created_at`, `updated_at`, `is_published`, `sort_order`) VALUES ('35', 'Interactive Q&A Session', 'Interactive Q&A session with special guests', '2026-10-24 00:00:00', '12:30', '14:00', 'session', NULL, 'Main Hall', NULL, '2026-02-04 20:00:11', '2026-02-20 15:03:12', '1', '1');
INSERT INTO `schedule_items` (`id`, `title`, `description`, `day`, `start_time`, `end_time`, `type`, `speaker_id`, `location`, `translations`, `created_at`, `updated_at`, `is_published`, `sort_order`) VALUES ('36', 'Healing Rooms', '15-minute personal ministry slots available upon prior registration.

You can register through the form available on the main page. Please note that the number of spots is limited, so applications will be considered on a first-come, first-served basis.', '2026-10-24 00:00:00', '14:30', '18:00', 'special', NULL, 'Healing Rooms', NULL, '2026-02-04 20:00:11', '2026-03-03 12:53:11', '1', '2');
INSERT INTO `schedule_items` (`id`, `title`, `description`, `day`, `start_time`, `end_time`, `type`, `speaker_id`, `location`, `translations`, `created_at`, `updated_at`, `is_published`, `sort_order`) VALUES ('37', 'Prayer Rooms', '15-minute personal ministry slots available upon prior registration.

You can register through the form available on the main page. Please note that the number of spots is limited, so applications will be considered on a first-come, first-served basis.', '2026-10-24 00:00:00', '14:30', '18:00', 'special', NULL, 'Prayer Rooms', NULL, '2026-02-04 20:00:11', '2026-03-09 10:31:47', '1', '3');
INSERT INTO `schedule_items` (`id`, `title`, `description`, `day`, `start_time`, `end_time`, `type`, `speaker_id`, `location`, `translations`, `created_at`, `updated_at`, `is_published`, `sort_order`) VALUES ('38', 'Street Evangelism', 'Outreach teams going into the city to share the Gospel.

You can register through the form available on the main page.', '2026-10-24 00:00:00', '14:30', '17:00', 'special', NULL, 'City Center', NULL, '2026-02-04 20:00:11', '2026-03-03 12:53:11', '1', '4');
INSERT INTO `schedule_items` (`id`, `title`, `description`, `day`, `start_time`, `end_time`, `type`, `speaker_id`, `location`, `translations`, `created_at`, `updated_at`, `is_published`, `sort_order`) VALUES ('39', 'Merch & Ministry Booths', 'Browse ministry resources and connect with partner organizations.', '2026-10-24 00:00:00', '14:30', '18:00', 'special', NULL, 'Foyer', NULL, '2026-02-04 20:00:11', '2026-02-04 20:00:11', '1', '5');
INSERT INTO `schedule_items` (`id`, `title`, `description`, `day`, `start_time`, `end_time`, `type`, `speaker_id`, `location`, `translations`, `created_at`, `updated_at`, `is_published`, `sort_order`) VALUES ('40', 'Workshops', 'Choose from workshops on Missions, Power Evangelism, Freedom from Homosexuality, Family, Father Heart of God, Marketplace Missions, Prophetic Arts, Pastoral Care, Prophetic Ministry, Prophetic, Human Trafficking, and Iris Global Alumni Gathering.', '2026-10-24 00:00:00', '16:00', '17:30', 'session', NULL, 'Various Rooms', NULL, '2026-02-04 20:00:11', '2026-03-09 11:19:13', '1', '6');
INSERT INTO `schedule_items` (`id`, `title`, `description`, `day`, `start_time`, `end_time`, `type`, `speaker_id`, `location`, `translations`, `created_at`, `updated_at`, `is_published`, `sort_order`) VALUES ('41', 'Saturday Evening Session', 'Worship, Guest Speaker and Ministry Time', '2026-10-24 00:00:00', '18:30', '22:00', 'session', NULL, 'Main Hall', NULL, '2026-02-04 20:00:11', '2026-02-20 15:03:12', '1', '7');
INSERT INTO `schedule_items` (`id`, `title`, `description`, `day`, `start_time`, `end_time`, `type`, `speaker_id`, `location`, `translations`, `created_at`, `updated_at`, `is_published`, `sort_order`) VALUES ('42', 'Sunday Morning Main Session', 'Worship, Guest Speaker and Ministry Time', '2026-10-25 00:00:00', '09:00', '12:00', 'session', NULL, 'Main Hall', NULL, '2026-02-04 20:00:11', '2026-02-20 15:03:12', '1', '0');
INSERT INTO `schedule_items` (`id`, `title`, `description`, `day`, `start_time`, `end_time`, `type`, `speaker_id`, `location`, `translations`, `created_at`, `updated_at`, `is_published`, `sort_order`) VALUES ('43', 'Sunday Afternoon Session', 'Worship, Guest Speaker and Ministry Time', '2026-10-25 00:00:00', '12:30', '14:00', 'session', NULL, 'Main Hall', NULL, '2026-02-04 20:00:11', '2026-02-20 15:03:12', '1', '1');
INSERT INTO `schedule_items` (`id`, `title`, `description`, `day`, `start_time`, `end_time`, `type`, `speaker_id`, `location`, `translations`, `created_at`, `updated_at`, `is_published`, `sort_order`) VALUES ('44', 'Healing Rooms', '15-minute personal ministry slots available upon prior registration.

You can register through the form available on the main page. Please note that the number of spots is limited, so applications will be considered on a first-come, first-served basis.', '2026-10-25 00:00:00', '14:30', '18:00', 'special', NULL, 'Healing Rooms', NULL, '2026-02-04 20:00:11', '2026-03-03 12:53:11', '1', '2');
INSERT INTO `schedule_items` (`id`, `title`, `description`, `day`, `start_time`, `end_time`, `type`, `speaker_id`, `location`, `translations`, `created_at`, `updated_at`, `is_published`, `sort_order`) VALUES ('45', 'Prayer Rooms', '15-minute personal ministry slots available upon prior registration.

You can register through the form available on the main page. Please note that the number of spots is limited, so applications will be considered on a first-come, first-served basis.', '2026-10-25 00:00:00', '14:30', '18:00', 'special', NULL, 'Prayer Rooms', NULL, '2026-02-04 20:00:11', '2026-03-09 10:31:47', '1', '3');
INSERT INTO `schedule_items` (`id`, `title`, `description`, `day`, `start_time`, `end_time`, `type`, `speaker_id`, `location`, `translations`, `created_at`, `updated_at`, `is_published`, `sort_order`) VALUES ('46', 'Street Evangelism', 'Outreach teams going into the city to share the Gospel.

You can register through the form available on the main page.', '2026-10-25 00:00:00', '14:30', '17:00', 'special', NULL, 'City Center', NULL, '2026-02-04 20:00:11', '2026-03-03 12:53:11', '1', '4');
INSERT INTO `schedule_items` (`id`, `title`, `description`, `day`, `start_time`, `end_time`, `type`, `speaker_id`, `location`, `translations`, `created_at`, `updated_at`, `is_published`, `sort_order`) VALUES ('47', 'Merch & Ministry Booths', 'Browse ministry resources and connect with partner organizations.', '2026-10-25 00:00:00', '14:30', '18:00', 'special', NULL, 'Foyer', NULL, '2026-02-04 20:00:11', '2026-02-04 20:00:11', '1', '5');
INSERT INTO `schedule_items` (`id`, `title`, `description`, `day`, `start_time`, `end_time`, `type`, `speaker_id`, `location`, `translations`, `created_at`, `updated_at`, `is_published`, `sort_order`) VALUES ('48', 'Workshops', 'Choose from workshops on Missions, Power Evangelism, Freedom from Homosexuality, Family, Father Heart of God, Marketplace Missions, Prophetic Arts, Pastoral Care, Prophetic Ministry, Prophetic, Human Trafficking, and Iris Global Alumni Gathering.', '2026-10-25 00:00:00', '16:00', '17:30', 'session', NULL, 'Various Rooms', NULL, '2026-02-04 20:00:11', '2026-03-09 11:19:13', '1', '6');
INSERT INTO `schedule_items` (`id`, `title`, `description`, `day`, `start_time`, `end_time`, `type`, `speaker_id`, `location`, `translations`, `created_at`, `updated_at`, `is_published`, `sort_order`) VALUES ('49', 'Closing Session', 'Worship, Guest Speaker and Ministry Time', '2026-10-25 00:00:00', '18:30', '22:00', 'session', NULL, 'Main Hall', NULL, '2026-02-04 20:00:11', '2026-02-20 15:03:12', '1', '7');

-- speakers (15 rows)
TRUNCATE TABLE `speakers`;
INSERT INTO `speakers` (`id`, `uuid`, `slug`, `name`, `title`, `organization`, `country`, `bio`, `photo_path`, `type`, `is_featured`, `sort_order`, `social_links`, `translations`, `created_at`, `updated_at`) VALUES ('1', '430bb215-f71e-42ac-881b-32991bb52cb3', 'heidi-baker', 'Heidi Baker', 'Missionary', 'Co-founder Iris Global', 'United States', 'Heidi''s greatest passion is to live in the manifest presence of God and to carry His glory, presence and love to His body and a lost and dying world. Rolland and Heidi Baker founded Iris Ministries, now Iris Global, in 1980. In 1995, they were called to the poorest country in the world at the time, Mozambique, and faced an extreme test of the Gospel. They began by pouring out their lives among abandoned street children, and as the Holy Spirit moved miraculously, a revival movement spread throughout Mozambique''s ten provinces. Heidi is now "Mama Aida" to thousands of people, overseeing a broad holistic ministry including Bible schools, medical clinics, church-based orphan care, and a network of thousands of churches.', 'images/speakers/heidi-baker.webp', 'speaker', '1', '2', NULL, NULL, '2026-01-27 13:55:25', '2026-03-18 10:09:36');
INSERT INTO `speakers` (`id`, `uuid`, `slug`, `name`, `title`, `organization`, `country`, `bio`, `photo_path`, `type`, `is_featured`, `sort_order`, `social_links`, `translations`, `created_at`, `updated_at`) VALUES ('2', '008157f7-efff-40bb-8214-44db3b42244d', 'mel-tari', 'Mel Tari', 'Evangelist', 'Author, Like a Mighty Wind', 'Indonesia', 'Indonesian born Mel Tari—affectionately known as "Papa Mel"—is a general of the faith. With a passionate zeal for God, Papa Mel is a sent out one that sprinkles the nations—and in turn—sends out masses into the harvest field, stoking the fires of revival through empowering, championing, divinely connecting, and building up the body. As the "Papa", he has been speaking at Iris Europe camps since their inception in 2021. Papa Mel is the author of "Like a Mighty Wind" that has inspired millions across the world.', 'images/speakers/Mel-Tari-1.webp', 'speaker', '1', '1', NULL, NULL, '2026-01-27 13:55:25', '2026-03-18 10:02:32');
INSERT INTO `speakers` (`id`, `uuid`, `slug`, `name`, `title`, `organization`, `country`, `bio`, `photo_path`, `type`, `is_featured`, `sort_order`, `social_links`, `translations`, `created_at`, `updated_at`) VALUES ('3', '1abd95e5-f08e-4866-b4c5-69e344f48c54', 'david-gava', 'David Gava', 'Missionary', 'Co-founder Kerusso', 'Sweden', 'David is originally from Zimbabwe, currently resides in Sweden with his wife Ingela and their two children. He is a missionary and founder of Kerusso Ministry in Sweden and Kerusso School in Brazil, which he leads alongside his family. He has spent more than two decades carrying a powerful testimony of resurrection and healing from a severe speech impediment that made public speaking a challenge until age 21—he is living proof that with God nothing is impossible. He is a servant leader, bathed in humility and gentleness, with wisdom from the King to lead an army of revivalists across the nations!', 'images/speakers/david-gava.webp', 'workshop_leader', '1', '2', NULL, NULL, '2026-01-27 13:55:25', '2026-03-18 10:09:36');
INSERT INTO `speakers` (`id`, `uuid`, `slug`, `name`, `title`, `organization`, `country`, `bio`, `photo_path`, `type`, `is_featured`, `sort_order`, `social_links`, `translations`, `created_at`, `updated_at`) VALUES ('4', '13768c16-1748-48a8-9b0a-45480b491cbc', 'pastor-josef', 'Pastor Josef', 'Guest Speaker', 'Budapest Church', 'Hungary', 'Pastor Josef leads one of Budapest''s vibrant churches and is a key voice in the Hungarian Christian community.', 'images/speakers/pastor-josef.webp', 'speaker', '0', '4', NULL, NULL, '2026-01-27 13:55:25', '2026-02-20 13:45:40');
INSERT INTO `speakers` (`id`, `uuid`, `slug`, `name`, `title`, `organization`, `country`, `bio`, `photo_path`, `type`, `is_featured`, `sort_order`, `social_links`, `translations`, `created_at`, `updated_at`) VALUES ('5', 'a42f6150-e520-4801-bf47-889cfb2dc0df', 'mary-pat-gokee', 'Mary Pat Gokee', 'Workshop Leader', 'Pastor, Frontlines Ministries International', 'United States', 'Mary Pat Gokee serves with Iris Global and leads prophetic arts workshops, combining creativity with the prophetic.', 'images/speakers/mary-pat-gokee.webp', 'workshop_leader', '0', '1', NULL, NULL, '2026-01-27 13:55:25', '2026-03-09 11:15:45');
INSERT INTO `speakers` (`id`, `uuid`, `slug`, `name`, `title`, `organization`, `country`, `bio`, `photo_path`, `type`, `is_featured`, `sort_order`, `social_links`, `translations`, `created_at`, `updated_at`) VALUES ('6', 'd88044c6-4794-47a2-bf44-7e2a57314989', 'katey-maddux', 'Katey Maddux', 'Workshop Leader', 'Founder, KBC & MWI', 'United States', 'Katey Maddux is a Kingdom builder and global leader dedicated to helping women walk in freedom, clarity, and bold obedience to God''s design for their lives and families. She is the Founder of Kingdom Business Collective, a global community for Christian women entrepreneurs and leaders, and Mighty Warrior International, a nonprofit focused on prevention, awareness, and strategic solutions in the fight against human trafficking and exploitation. Her work takes shape at the intersection of business, ministry, and global mission, with initiatives and partnerships across the U.S., Europe, Africa, and Asia.', 'images/speakers/Katey.webp', 'workshop_leader', '0', '12', NULL, NULL, '2026-01-27 13:55:25', '2026-02-04 19:41:18');
INSERT INTO `speakers` (`id`, `uuid`, `slug`, `name`, `title`, `organization`, `country`, `bio`, `photo_path`, `type`, `is_featured`, `sort_order`, `social_links`, `translations`, `created_at`, `updated_at`) VALUES ('7', '47e9d52c-bb0a-4961-8a55-56c7e79b8fd8', 'baoyan-lam', 'Baoyan Lam & Rudy Taslim', 'Workshop Leader', 'Founders Iris Singapore & Living Oaks', 'China', 'Baoyan Lam serves with Iris Asia and brings wisdom and practical teaching on family and parenting from a biblical perspective.', 'images/speakers/baoyan-lam.webp', 'speaker', '0', '11', NULL, NULL, '2026-01-27 13:55:25', '2026-03-09 11:17:25');
INSERT INTO `speakers` (`id`, `uuid`, `slug`, `name`, `title`, `organization`, `country`, `bio`, `photo_path`, `type`, `is_featured`, `sort_order`, `social_links`, `translations`, `created_at`, `updated_at`) VALUES ('8', '1a50a870-ecd8-4d44-951f-cc49378e6687', 'tineke-bouwman', 'Tineke Bouwman', 'Workshop Leader', 'Founder, Lighthouse Ministries', 'Netherlands', 'Tineke Bouwman is the founder and forerunner of Lighthouse Ministries in Rilland, the Netherlands. As a prophetic voice in this generation, she brings breakthrough and stirs fire in the hearts of those she ministers to—releasing destiny. Lighthouse is a ministry born from walking in God-given prophetic revelation. It is a Family Home (community-centered living for young adults); a house of prayer; a church; and a training center. What started with a simple yes has grown into a prophetic movement. Tineke has raised up a generation burning for Jesus who understand the value of intimate life with God. She works internationally as a counselor and trainer of leaders. A mother of five children (including a foster daughter) and eight grandchildren, she gratefully enjoys time at home with her family when she is not running with God among the nations.', 'images/speakers/tineke-bouwman.webp', 'workshop_leader', '0', '10', NULL, NULL, '2026-02-06 15:11:13', '2026-03-09 11:15:45');
INSERT INTO `speakers` (`id`, `uuid`, `slug`, `name`, `title`, `organization`, `country`, `bio`, `photo_path`, `type`, `is_featured`, `sort_order`, `social_links`, `translations`, `created_at`, `updated_at`) VALUES ('9', 'd529932b-e0dd-499d-9b2b-a7914b75290f', 'awakening-music', 'Awakening Music', 'Worship Team', NULL, NULL, NULL, 'images/speakers/awakening-music.webp', 'worship_team', '0', '1', NULL, NULL, '2026-02-20 13:55:42', '2026-02-20 14:05:49');
INSERT INTO `speakers` (`id`, `uuid`, `slug`, `name`, `title`, `organization`, `country`, `bio`, `photo_path`, `type`, `is_featured`, `sort_order`, `social_links`, `translations`, `created_at`, `updated_at`) VALUES ('11', 'b9990c35-02e5-4150-9c74-d894390ebc63', 'ania-adam', 'Ania & Adam', 'Workshop Leader', NULL, NULL, NULL, NULL, 'workshop_leader', '0', '4', NULL, NULL, '2026-03-09 11:15:45', '2026-03-09 11:15:45');
INSERT INTO `speakers` (`id`, `uuid`, `slug`, `name`, `title`, `organization`, `country`, `bio`, `photo_path`, `type`, `is_featured`, `sort_order`, `social_links`, `translations`, `created_at`, `updated_at`) VALUES ('12', 'f4635f12-9a68-4d8f-9e94-3c4e7d293ddb', 'brian-valerie', 'Brian & Valerie', 'Workshop Leader', NULL, NULL, NULL, NULL, 'workshop_leader', '0', '5', NULL, NULL, '2026-03-09 11:15:45', '2026-03-09 11:15:45');
INSERT INTO `speakers` (`id`, `uuid`, `slug`, `name`, `title`, `organization`, `country`, `bio`, `photo_path`, `type`, `is_featured`, `sort_order`, `social_links`, `translations`, `created_at`, `updated_at`) VALUES ('13', 'f9accc8a-1f00-4d84-84b5-cf03f7861062', 'yan-rudy', 'Yan & Rudy', 'Workshop Leader', NULL, NULL, NULL, NULL, 'workshop_leader', '0', '6', NULL, NULL, '2026-03-09 11:15:45', '2026-03-09 11:15:45');
INSERT INTO `speakers` (`id`, `uuid`, `slug`, `name`, `title`, `organization`, `country`, `bio`, `photo_path`, `type`, `is_featured`, `sort_order`, `social_links`, `translations`, `created_at`, `updated_at`) VALUES ('14', '4b7b8c98-ae7f-41c1-8d25-6ff9c2fab1ea', 'teisa-jean', 'Teisa & Jean', 'Workshop Leader', NULL, NULL, NULL, NULL, 'workshop_leader', '0', '7', NULL, NULL, '2026-03-09 11:15:45', '2026-03-09 11:15:45');
INSERT INTO `speakers` (`id`, `uuid`, `slug`, `name`, `title`, `organization`, `country`, `bio`, `photo_path`, `type`, `is_featured`, `sort_order`, `social_links`, `translations`, `created_at`, `updated_at`) VALUES ('15', '08c85da2-2530-4ab2-ade0-1e6ac6df2107', 'dr-kate', 'Dr. Kate', 'Workshop Leader', NULL, NULL, NULL, NULL, 'workshop_leader', '0', '8', NULL, NULL, '2026-03-09 11:15:45', '2026-03-09 11:15:45');
INSERT INTO `speakers` (`id`, `uuid`, `slug`, `name`, `title`, `organization`, `country`, `bio`, `photo_path`, `type`, `is_featured`, `sort_order`, `social_links`, `translations`, `created_at`, `updated_at`) VALUES ('17', '6455001a-1ed1-4b46-a28e-e33551077177', 'cyndi-tim-byrd', 'Cyndi & Tim Byrd', 'Workshop Leader', NULL, NULL, NULL, NULL, 'workshop_leader', '0', '11', NULL, NULL, '2026-03-09 11:15:45', '2026-03-09 11:15:45');

-- sponsors (4 rows)
TRUNCATE TABLE `sponsors`;
INSERT INTO `sponsors` (`id`, `name`, `logo_path`, `website_url`, `tier`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('1', 'Iris Krakow', 'resources/images/iris-krakow-logo.webp', 'https://iriskrakow.org', 'platinum', '1', '1', '2026-01-27 13:55:25', '2026-02-20 15:16:18');
INSERT INTO `sponsors` (`id`, `name`, `logo_path`, `website_url`, `tier`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('2', 'Kingdom Business Collective', 'resources/images/partner-logos/KBC-Logo.png', NULL, 'gold', '10', '1', '2026-01-27 13:55:25', '2026-02-04 21:09:48');
INSERT INTO `sponsors` (`id`, `name`, `logo_path`, `website_url`, `tier`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('3', 'Mighty Warrior International', 'resources/images/partner-logos/MWI-Logo.png', NULL, 'gold', '11', '1', '2026-01-27 13:55:25', '2026-02-04 21:09:48');
INSERT INTO `sponsors` (`id`, `name`, `logo_path`, `website_url`, `tier`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('4', 'Kerusso', 'resources/images/partner-logos/Kerusso.png', 'https://kerusso.com', 'gold', '12', '1', '2026-01-27 13:55:25', '2026-02-04 21:09:48');

-- ticket_prices (8 rows)
TRUNCATE TABLE `ticket_prices`;
INSERT INTO `ticket_prices` (`id`, `uuid`, `ticket_type`, `pricing_tier`, `price`, `label`, `description`, `is_active`, `sort_order`, `created_at`, `updated_at`) VALUES ('1', '6721125d-8a04-400a-90ca-ea33abace7d2', '3day', 'early', '4900', '3-Day Pass', NULL, '1', '3', '2026-02-06 17:24:09', '2026-02-23 14:56:46');
INSERT INTO `ticket_prices` (`id`, `uuid`, `ticket_type`, `pricing_tier`, `price`, `label`, `description`, `is_active`, `sort_order`, `created_at`, `updated_at`) VALUES ('2', 'f3671636-0f12-43e2-a5ba-6b8215582123', '3day', 'regular', '6900', '3-Day Pass', NULL, '1', '3', '2026-02-06 17:24:09', '2026-02-23 14:56:46');
INSERT INTO `ticket_prices` (`id`, `uuid`, `ticket_type`, `pricing_tier`, `price`, `label`, `description`, `is_active`, `sort_order`, `created_at`, `updated_at`) VALUES ('3', '7b7e906b-8a21-49c9-994e-e6f4f9edabfc', 'group', 'early', '3900', 'Group Ticket', NULL, '1', '5', '2026-02-06 17:24:09', '2026-02-23 14:56:46');
INSERT INTO `ticket_prices` (`id`, `uuid`, `ticket_type`, `pricing_tier`, `price`, `label`, `description`, `is_active`, `sort_order`, `created_at`, `updated_at`) VALUES ('4', '57266a86-aca3-48bd-af4f-cdd69ab135d6', 'group', 'regular', '5900', 'Group Ticket', NULL, '1', '5', '2026-02-06 17:24:09', '2026-02-23 14:56:46');
INSERT INTO `ticket_prices` (`id`, `uuid`, `ticket_type`, `pricing_tier`, `price`, `label`, `description`, `is_active`, `sort_order`, `created_at`, `updated_at`) VALUES ('5', 'df7d3960-3748-4680-b9e6-24944e161e47', 'volunteer', 'early', '2900', 'Volunteer Pass', NULL, '0', '5', '2026-02-06 17:24:09', '2026-02-23 14:56:46');
INSERT INTO `ticket_prices` (`id`, `uuid`, `ticket_type`, `pricing_tier`, `price`, `label`, `description`, `is_active`, `sort_order`, `created_at`, `updated_at`) VALUES ('6', '8a4db5cb-4ed4-4018-9f1c-602453652982', 'volunteer', 'regular', '3900', 'Volunteer Pass', NULL, '0', '6', '2026-02-06 17:24:09', '2026-02-23 14:56:46');
INSERT INTO `ticket_prices` (`id`, `uuid`, `ticket_type`, `pricing_tier`, `price`, `label`, `description`, `is_active`, `sort_order`, `created_at`, `updated_at`) VALUES ('7', 'dc1aa93c-0ff8-477d-a5fe-b3f872151a10', '1day', 'early', '2900', '1-Day Pass', NULL, '1', '1', '2026-02-23 14:56:46', '2026-02-23 14:56:46');
INSERT INTO `ticket_prices` (`id`, `uuid`, `ticket_type`, `pricing_tier`, `price`, `label`, `description`, `is_active`, `sort_order`, `created_at`, `updated_at`) VALUES ('8', '866ea668-69bf-4cb5-832a-fb431c170ee0', '1day', 'regular', '3900', '1-Day Pass', NULL, '1', '2', '2026-02-23 14:56:46', '2026-02-23 14:56:46');

-- users (4 rows)
TRUNCATE TABLE `users`;
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `is_admin`) VALUES ('1', 'Test User', 'test@example.com', '2026-01-27 13:55:25', '$2y$12$JtZnVPWFosp2WVfeakm/h.CpoUqlhey5ZY7WaCAAIhRz0../EQHaa', 'vCk3kIOqKl', '2026-01-27 13:55:25', '2026-01-27 13:55:25', NULL, NULL, NULL, '0');
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `is_admin`) VALUES ('2', 'Admin', 'admin@europeRevival.com', '2026-01-27 13:55:26', '$2y$12$yrkkrkGPGenbZ5SqMwx2rebEsU82BBl4v7GXEroFnatj2bt2T5fd2', NULL, '2026-01-27 13:55:26', '2026-01-27 13:55:26', NULL, NULL, NULL, '1');
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `is_admin`) VALUES ('3', 'Admin User', 'admin@admin.com', '2026-01-27 13:55:26', '$2y$12$KuDFzgaPWkMXVHwGQXMbUe9SCEOvadaLFG7/0f6SCN4CJ57dYrRhm', 'grI5rjUZex', '2026-01-27 13:55:26', '2026-01-27 13:55:26', NULL, NULL, NULL, '1');
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `is_admin`) VALUES ('4', 'Admin', 'dhegedus100@gmail.com', NULL, '$2y$12$q07bNcDeUEq2ogXGIgObze9pSmjVf6FwsSxD/bJUPj1adxjDwAFYq', NULL, '2026-03-18 13:39:11', '2026-03-18 13:39:11', NULL, NULL, NULL, '1');

-- workshops (11 rows)
TRUNCATE TABLE `workshops`;
INSERT INTO `workshops` (`id`, `uuid`, `slug`, `title`, `short_description`, `description`, `benefits`, `speaker_id`, `image_path`, `capacity`, `duration_minutes`, `difficulty_level`, `requirements`, `is_published`, `sort_order`, `translations`, `created_at`, `updated_at`, `leader_name`, `schedule_note`, `date`) VALUES ('6', 'cb8d985c-e057-47e7-9610-114dc4362771', 'power-evangelism', 'Power Evangelism', 'Learn to step out in boldness and share the Gospel with signs and wonders following.', 'David Gava shares from years of front-line experience in power evangelism across nations. Learn how to hear the Holy Spirit for words of knowledge on the streets, pray for the sick, and lead people to Jesus with confidence and compassion.', NULL, '3', NULL, NULL, '90', 'all', NULL, '1', '2', NULL, '2026-02-06 16:19:50', '2026-03-13 12:59:00', 'David Gava', 'Saturday', '2026-10-23');
INSERT INTO `workshops` (`id`, `uuid`, `slug`, `title`, `short_description`, `description`, `benefits`, `speaker_id`, `image_path`, `capacity`, `duration_minutes`, `difficulty_level`, `requirements`, `is_published`, `sort_order`, `translations`, `created_at`, `updated_at`, `leader_name`, `schedule_note`, `date`) VALUES ('8', '2cdb39a8-1b7f-4a2e-824f-b0ca1145b0d3', 'prophetic-arts', 'Prophetic Arts', 'Express worship and prophetic revelation through creative arts and visual media.', 'Discover how to tap into the creative flow of the Holy Spirit. This hands-on workshop explores painting, drawing, and other visual arts as expressions of worship and prophetic revelation.', NULL, '15', NULL, NULL, '90', 'all', NULL, '1', '8', NULL, '2026-02-06 16:19:50', '2026-03-13 12:59:00', 'Dr. Kate', 'Saturday & Sunday', '2026-10-23');
INSERT INTO `workshops` (`id`, `uuid`, `slug`, `title`, `short_description`, `description`, `benefits`, `speaker_id`, `image_path`, `capacity`, `duration_minutes`, `difficulty_level`, `requirements`, `is_published`, `sort_order`, `translations`, `created_at`, `updated_at`, `leader_name`, `schedule_note`, `date`) VALUES ('9', '9cf7c23f-0703-4aec-87c6-6f15aa646954', 'prophetic-ministry', 'Prophetic', 'Grow in the prophetic gift and learn to minister with accuracy and love.', 'Tineke Bouwman, a seasoned prophetic voice, teaches how to hear God''s voice clearly, deliver prophetic words with accuracy and love, and grow in this vital gift for the building up of the body of Christ.', NULL, '8', NULL, NULL, '90', 'all', NULL, '1', '10', NULL, '2026-02-06 16:19:50', '2026-03-13 12:59:00', 'Tineke Bouwman', 'Saturday & Sunday', '2026-10-23');
INSERT INTO `workshops` (`id`, `uuid`, `slug`, `title`, `short_description`, `description`, `benefits`, `speaker_id`, `image_path`, `capacity`, `duration_minutes`, `difficulty_level`, `requirements`, `is_published`, `sort_order`, `translations`, `created_at`, `updated_at`, `leader_name`, `schedule_note`, `date`) VALUES ('11', '5ce95aaa-0692-4020-8298-148fdd5c46bd', 'missions', 'Missions', 'Catch a vision for global missions and learn practical steps to answer the call.', 'Mary Pat Gokee shares from her experience with Iris Global to inspire and equip you for cross-cultural missions, whether short-term or long-term. Learn about the harvest fields and how you can participate.', NULL, '5', NULL, NULL, '90', 'all', NULL, '1', '1', NULL, '2026-02-06 16:19:50', '2026-03-13 12:59:00', 'Mary Pat Gokee', 'Saturday & Sunday', '2026-10-23');
INSERT INTO `workshops` (`id`, `uuid`, `slug`, `title`, `short_description`, `description`, `benefits`, `speaker_id`, `image_path`, `capacity`, `duration_minutes`, `difficulty_level`, `requirements`, `is_published`, `sort_order`, `translations`, `created_at`, `updated_at`, `leader_name`, `schedule_note`, `date`) VALUES ('12', '29d7760f-b562-454f-9b15-bba7ab3eb39e', 'marketplace-missions', 'Marketplace Missions', 'Transform your workplace into a mission field and integrate faith with business.', 'Yan & Rudy share how to carry the Kingdom of God into the marketplace. Discover how your business and professional skills can be used for eternal impact and how to be a missionary wherever you work.', NULL, '13', NULL, NULL, '90', 'all', NULL, '1', '6', NULL, '2026-02-06 16:19:50', '2026-03-13 12:59:00', 'Yan & Rudy', 'Saturday & Sunday', '2026-10-23');
INSERT INTO `workshops` (`id`, `uuid`, `slug`, `title`, `short_description`, `description`, `benefits`, `speaker_id`, `image_path`, `capacity`, `duration_minutes`, `difficulty_level`, `requirements`, `is_published`, `sort_order`, `translations`, `created_at`, `updated_at`, `leader_name`, `schedule_note`, `date`) VALUES ('13', 'd5f0d064-85fe-4e2a-931f-3f60c5df0590', 'family', 'Family', 'Biblical foundations for building strong, God-centered families in today''s world.', 'Baoyan Lam brings wisdom and practical teaching on family and parenting from a biblical perspective. Learn how to build a God-honoring family culture and raise children who love Jesus.', NULL, '11', NULL, NULL, '90', 'all', NULL, '1', '4', NULL, '2026-02-06 16:19:50', '2026-03-13 12:59:00', 'Baoyan Lam', 'Saturday & Sunday', '2026-10-23');
INSERT INTO `workshops` (`id`, `uuid`, `slug`, `title`, `short_description`, `description`, `benefits`, `speaker_id`, `image_path`, `capacity`, `duration_minutes`, `difficulty_level`, `requirements`, `is_published`, `sort_order`, `translations`, `created_at`, `updated_at`, `leader_name`, `schedule_note`, `date`) VALUES ('14', 'ec4ec7ab-6278-4208-abfc-fd466307f637', 'human-trafficking-awareness', 'Human Trafficking', 'Awareness, prevention, and strategic solutions in the fight against exploitation.', 'Katey Maddux, founder of Mighty Warrior International, shares critical awareness about human trafficking and practical ways the church can engage in prevention, rescue, and restoration efforts.', NULL, '6', NULL, NULL, '90', 'all', NULL, '1', '12', NULL, '2026-02-06 16:19:50', '2026-03-13 12:59:00', 'Katey Maddux', 'Saturday & Sunday', '2026-10-23');
INSERT INTO `workshops` (`id`, `uuid`, `slug`, `title`, `short_description`, `description`, `benefits`, `speaker_id`, `image_path`, `capacity`, `duration_minutes`, `difficulty_level`, `requirements`, `is_published`, `sort_order`, `translations`, `created_at`, `updated_at`, `leader_name`, `schedule_note`, `date`) VALUES ('16', 'dcc2d19c-8957-42ba-9d83-96269850553f', 'father-heart-of-god', 'Father Heart of God', 'Encounter the deep, unconditional love of your Heavenly Father.', 'Brian & Valerie lead a transformative workshop on experiencing the Father''s love. Discover the healing power of understanding your identity as a beloved child of God.', NULL, '12', NULL, NULL, '90', 'all', NULL, '1', '5', NULL, '2026-02-06 16:19:50', '2026-03-13 12:59:00', 'Brian & Valerie', 'Saturday & Sunday', '2026-10-23');
INSERT INTO `workshops` (`id`, `uuid`, `slug`, `title`, `short_description`, `description`, `benefits`, `speaker_id`, `image_path`, `capacity`, `duration_minutes`, `difficulty_level`, `requirements`, `is_published`, `sort_order`, `translations`, `created_at`, `updated_at`, `leader_name`, `schedule_note`, `date`) VALUES ('17', 'c63ebe2b-7b99-42d8-8f07-71bf65360894', 'iris-global-alumni-gathering', 'Iris Global Alumni Gathering', 'A special reunion for Iris Harvest School of Missions alumni and friends.', 'Heidi Baker and Iris missionaries host a special gathering for alumni of the Iris Global Harvest School of Missions. Reconnect, share testimonies, and be refreshed together.', NULL, '1', NULL, NULL, '90', 'all', NULL, '1', '13', NULL, '2026-02-06 16:19:50', '2026-03-13 12:59:00', 'Heidi Baker & Iris Missionaries', 'Sunday only', '2026-10-23');
INSERT INTO `workshops` (`id`, `uuid`, `slug`, `title`, `short_description`, `description`, `benefits`, `speaker_id`, `image_path`, `capacity`, `duration_minutes`, `difficulty_level`, `requirements`, `is_published`, `sort_order`, `translations`, `created_at`, `updated_at`, `leader_name`, `schedule_note`, `date`) VALUES ('18', 'd7ef6fde-805b-4f9c-b854-4673eaa633ae', 'missions-teisa-jean', 'Missions', NULL, 'Teisa & Jean share their journey and insights on cross-cultural missions and reaching the nations.', NULL, '14', NULL, NULL, '120', 'all', NULL, '1', '7', NULL, '2026-03-09 11:17:40', '2026-03-13 12:59:00', NULL, NULL, '2026-10-23');
INSERT INTO `workshops` (`id`, `uuid`, `slug`, `title`, `short_description`, `description`, `benefits`, `speaker_id`, `image_path`, `capacity`, `duration_minutes`, `difficulty_level`, `requirements`, `is_published`, `sort_order`, `translations`, `created_at`, `updated_at`, `leader_name`, `schedule_note`, `date`) VALUES ('19', '36bc6f4c-8705-49b4-8db6-dbe26906fb29', 'prophetic-cyndi-tim', 'Prophetic', NULL, 'Cyndi & Tim Byrd lead a hands-on workshop exploring the prophetic gifts and hearing God''s voice.', NULL, '17', NULL, NULL, '120', 'all', NULL, '1', '11', NULL, '2026-03-09 11:17:40', '2026-03-13 12:59:00', NULL, NULL, '2026-10-23');

SET FOREIGN_KEY_CHECKS = 1;
